# Dockerfile para el sitio web estático (dentro de la carpeta pagina_web/)

# Usar una imagen oficial de Nginx, que es un servidor web ultraligero y de alto rendimiento.
FROM nginx:alpine

# Copiar los archivos de tu página (html, css, js) al directorio por defecto de Nginx.
COPY . /usr/share/nginx/html